### ISSUE TITLE
Use origin in example to prevent duplicate packets from hitting the wire

### ISSUE THREAD

**Issue by Flamenco** [yjs/docs#16]
> Please save me some time and use the following template. In 90% of all issues I can't reproduce the problem because I don't know what exactly you are doing, in which environment, or which y-* version is responsible. Just use the following template even if you think the problem is obvious.

**Checklist**

* [x] Are you reporting a bug? Use github issues for bug reports and feature requests. For general questions, please use https://discuss.yjs.dev/
* [x] Try to report your issue in the correct repository. Yjs consists of many modules. When in doubt, report it to https://github.com/yjs/yjs/issues/

**Describe the bug**
Add and example of syncing clients using transact and origin to eliminate cycles.

When I followed the example to implement a custom websocket provider, every client resent the update to the server until  I checked if the update originated from the client before sending.

**Comment by Flamenco** [comment]
I added a feature request as well, related to this.

https://github.com/yjs/yjs/issues/321

**Comment by dmonad** [comment]
Yeah, it would be nice to have an example for this. Thanks for the suggestion.

**Comment by Flamenco** [comment]
The example you provided on my pull request was quite helpful.  Thanks again!
