### ISSUE TITLE
Copy and paste from the docs site does not appear to work across elements

### ISSUE THREAD

**Issue by reivilibre** [yjs/docs#32]
**Describe the bug**
If you try to select some passages from the documentation (including text containing links, or documentation about event listeners), for some reason you can't and only get one fragment of text.

**To Reproduce**
1. Go to https://docs.yjs.dev/ecosystem/connection-provider/y-websocket
2. Copy the first bullet point
3. Paste somewhere else, notice it gets truncated to: 'Supports cross-tab communication. When you open the same document in the same browser, changes on the document are exchanged via cross-tab communication ('

**Expected behavior**
I should be able to copy the whole bullet point of text, even if it's not formatted in the best way :-).

**Environment Information**
 - Firefox 96.0 on Linux
 - Docs site as of 2022-02-24

**Comment by dmonad** [comment]
Hi @reivilibre,

thanks for your feedback!

Unfortunately, I can't solve this problem as I'm hosting the docs on gitbook.com and I have no control over how the data is rendered.

There is a possibility that this is a Firefox issue. I think Firefox performs some custom cleanup that doesn't always make sense. Dragging content (select, and then move the selected text to a different editor) doesn't perform cleanup and works much better.

Cheers, -

**Comment by reivilibre** [comment]
> There is a possibility that this is a Firefox issue

I have never ever seen this issue before; I would expect GitBook would have to be doing something very weird and wacky to cause this, but I don't know.

I've contacted GitBook about it since it's frustrating enough; who knows if they'll get back to me on it though.
